// Comprehensive countries and subdivisions data for production use
// This data structure supports international addresses with proper country codes and subdivisions

export interface Country {
  code: string;
  name: string;
  hasStates: boolean;
  zipLabel: string; // ZIP, Postal Code, etc.
  phoneCode: string;
}

export interface Subdivision {
  code: string;
  name: string;
}

export const countries: Country[] = [
  { code: "US", name: "United States", hasStates: true, zipLabel: "ZIP Code", phoneCode: "+1" },
  { code: "CA", name: "Canada", hasStates: true, zipLabel: "Postal Code", phoneCode: "+1" },
  { code: "GB", name: "United Kingdom", hasStates: false, zipLabel: "Postcode", phoneCode: "+44" },
  { code: "AU", name: "Australia", hasStates: true, zipLabel: "Postcode", phoneCode: "+61" },
  { code: "DE", name: "Germany", hasStates: true, zipLabel: "PLZ", phoneCode: "+49" },
  { code: "FR", name: "France", hasStates: false, zipLabel: "Code Postal", phoneCode: "+33" },
  { code: "IT", name: "Italy", hasStates: false, zipLabel: "CAP", phoneCode: "+39" },
  { code: "ES", name: "Spain", hasStates: false, zipLabel: "Código Postal", phoneCode: "+34" },
  { code: "NL", name: "Netherlands", hasStates: false, zipLabel: "Postcode", phoneCode: "+31" },
  { code: "BE", name: "Belgium", hasStates: false, zipLabel: "Code Postal", phoneCode: "+32" },
  { code: "CH", name: "Switzerland", hasStates: false, zipLabel: "PLZ", phoneCode: "+41" },
  { code: "AT", name: "Austria", hasStates: false, zipLabel: "PLZ", phoneCode: "+43" },
  { code: "SE", name: "Sweden", hasStates: false, zipLabel: "Postnummer", phoneCode: "+46" },
  { code: "NO", name: "Norway", hasStates: false, zipLabel: "Postnummer", phoneCode: "+47" },
  { code: "DK", name: "Denmark", hasStates: false, zipLabel: "Postnummer", phoneCode: "+45" },
  { code: "FI", name: "Finland", hasStates: false, zipLabel: "Postinumero", phoneCode: "+358" },
  { code: "JP", name: "Japan", hasStates: false, zipLabel: "郵便番号", phoneCode: "+81" },
  { code: "KR", name: "South Korea", hasStates: false, zipLabel: "우편번호", phoneCode: "+82" },
  { code: "CN", name: "China", hasStates: true, zipLabel: "邮政编码", phoneCode: "+86" },
  { code: "IN", name: "India", hasStates: true, zipLabel: "PIN Code", phoneCode: "+91" },
  { code: "BR", name: "Brazil", hasStates: true, zipLabel: "CEP", phoneCode: "+55" },
  { code: "MX", name: "Mexico", hasStates: true, zipLabel: "Código Postal", phoneCode: "+52" },
  { code: "AR", name: "Argentina", hasStates: true, zipLabel: "Código Postal", phoneCode: "+54" },
  { code: "CO", name: "Colombia", hasStates: true, zipLabel: "Código Postal", phoneCode: "+57" },
  { code: "PE", name: "Peru", hasStates: true, zipLabel: "Código Postal", phoneCode: "+51" },
  { code: "CL", name: "Chile", hasStates: true, zipLabel: "Código Postal", phoneCode: "+56" },
  { code: "ZA", name: "South Africa", hasStates: false, zipLabel: "Postal Code", phoneCode: "+27" },
  { code: "NG", name: "Nigeria", hasStates: true, zipLabel: "Postal Code", phoneCode: "+234" },
  { code: "EG", name: "Egypt", hasStates: false, zipLabel: "Postal Code", phoneCode: "+20" },
  { code: "KE", name: "Kenya", hasStates: false, zipLabel: "Postal Code", phoneCode: "+254" },
  { code: "GH", name: "Ghana", hasStates: false, zipLabel: "Postal Code", phoneCode: "+233" },
  { code: "TZ", name: "Tanzania", hasStates: false, zipLabel: "Postal Code", phoneCode: "+255" },
  { code: "UG", name: "Uganda", hasStates: false, zipLabel: "Postal Code", phoneCode: "+256" },
  { code: "RW", name: "Rwanda", hasStates: false, zipLabel: "Province", phoneCode: "+250" },
  { code: "SN", name: "Senegal", hasStates: false, zipLabel: "Code Postal", phoneCode: "+221" },
  { code: "MA", name: "Morocco", hasStates: false, zipLabel: "Code Postal", phoneCode: "+212" },
  { code: "TN", name: "Tunisia", hasStates: false, zipLabel: "Code Postal", phoneCode: "+216" },
  { code: "AE", name: "United Arab Emirates", hasStates: false, zipLabel: "PO Box", phoneCode: "+971" },
  { code: "SA", name: "Saudi Arabia", hasStates: false, zipLabel: "Postal Code", phoneCode: "+966" },
  { code: "IL", name: "Israel", hasStates: false, zipLabel: "מיקוד", phoneCode: "+972" },
  { code: "TR", name: "Turkey", hasStates: false, zipLabel: "Posta Kodu", phoneCode: "+90" },
  { code: "TH", name: "Thailand", hasStates: false, zipLabel: "รหัสไปรษณีย์", phoneCode: "+66" },
  { code: "MY", name: "Malaysia", hasStates: true, zipLabel: "Poskod", phoneCode: "+60" },
  { code: "SG", name: "Singapore", hasStates: false, zipLabel: "Postal Code", phoneCode: "+65" },
  { code: "PH", name: "Philippines", hasStates: false, zipLabel: "ZIP Code", phoneCode: "+63" },
  { code: "ID", name: "Indonesia", hasStates: true, zipLabel: "Kode Pos", phoneCode: "+62" },
  { code: "VN", name: "Vietnam", hasStates: false, zipLabel: "Mã bưu chính", phoneCode: "+84" },
  { code: "PK", name: "Pakistan", hasStates: true, zipLabel: "Postal Code", phoneCode: "+92" },
  { code: "BD", name: "Bangladesh", hasStates: false, zipLabel: "Post Code", phoneCode: "+880" },
  { code: "LK", name: "Sri Lanka", hasStates: false, zipLabel: "Postal Code", phoneCode: "+94" },
  { code: "NP", name: "Nepal", hasStates: false, zipLabel: "Postal Code", phoneCode: "+977" },
  { code: "NZ", name: "New Zealand", hasStates: false, zipLabel: "Postcode", phoneCode: "+64" },
  { code: "PT", name: "Portugal", hasStates: false, zipLabel: "Código Postal", phoneCode: "+351" },
  { code: "GR", name: "Greece", hasStates: false, zipLabel: "T.K.", phoneCode: "+30" },
  { code: "PL", name: "Poland", hasStates: false, zipLabel: "Kod pocztowy", phoneCode: "+48" },
  { code: "CZ", name: "Czech Republic", hasStates: false, zipLabel: "PSČ", phoneCode: "+420" },
  { code: "HU", name: "Hungary", hasStates: false, zipLabel: "Irányítószám", phoneCode: "+36" },
  { code: "RO", name: "Romania", hasStates: false, zipLabel: "Cod poștal", phoneCode: "+40" },
  { code: "SK", name: "Slovakia", hasStates: false, zipLabel: "PSČ", phoneCode: "+421" },
  { code: "SI", name: "Slovenia", hasStates: false, zipLabel: "Poštna številka", phoneCode: "+386" },
  { code: "HR", name: "Croatia", hasStates: false, zipLabel: "Poštanski broj", phoneCode: "+385" },
  { code: "BA", name: "Bosnia and Herzegovina", hasStates: false, zipLabel: "Poštanski broj", phoneCode: "+387" },
  { code: "RS", name: "Serbia", hasStates: false, zipLabel: "Poštanski broj", phoneCode: "+381" },
  { code: "ME", name: "Montenegro", hasStates: false, zipLabel: "Poštanski broj", phoneCode: "+382" },
  { code: "MK", name: "North Macedonia", hasStates: false, zipLabel: "Поштенски код", phoneCode: "+389" },
  { code: "AL", name: "Albania", hasStates: false, zipLabel: "Kodi Postar", phoneCode: "+355" },
  { code: "BG", name: "Bulgaria", hasStates: false, zipLabel: "Пощенски код", phoneCode: "+359" },
  { code: "EE", name: "Estonia", hasStates: false, zipLabel: "Postiindeks", phoneCode: "+372" },
  { code: "LV", name: "Latvia", hasStates: false, zipLabel: "Pasta indekss", phoneCode: "+371" },
  { code: "LT", name: "Lithuania", hasStates: false, zipLabel: "Pašto kodas", phoneCode: "+370" },
  { code: "IE", name: "Ireland", hasStates: false, zipLabel: "Eircode", phoneCode: "+353" },
  { code: "LU", name: "Luxembourg", hasStates: false, zipLabel: "Code Postal", phoneCode: "+352" },
  { code: "MT", name: "Malta", hasStates: false, zipLabel: "Postcode", phoneCode: "+356" },
  { code: "CY", name: "Cyprus", hasStates: false, zipLabel: "T.K.", phoneCode: "+357" },
  { code: "IS", name: "Iceland", hasStates: false, zipLabel: "Póstnúmer", phoneCode: "+354" },
  { code: "LI", name: "Liechtenstein", hasStates: false, zipLabel: "PLZ", phoneCode: "+423" },
  { code: "MC", name: "Monaco", hasStates: false, zipLabel: "Code Postal", phoneCode: "+377" },
  { code: "SM", name: "San Marino", hasStates: false, zipLabel: "CAP", phoneCode: "+378" },
  { code: "VA", name: "Vatican City", hasStates: false, zipLabel: "CAP", phoneCode: "+379" },
  { code: "AD", name: "Andorra", hasStates: false, zipLabel: "Codi Postal", phoneCode: "+376" },
  { code: "GI", name: "Gibraltar", hasStates: false, zipLabel: "Postcode", phoneCode: "+350" },
  { code: "GG", name: "Guernsey", hasStates: false, zipLabel: "Postcode", phoneCode: "+44" },
  { code: "JE", name: "Jersey", hasStates: false, zipLabel: "Postcode", phoneCode: "+44" },
  { code: "IM", name: "Isle of Man", hasStates: false, zipLabel: "Postcode", phoneCode: "+44" },
  { code: "FO", name: "Faroe Islands", hasStates: false, zipLabel: "Postnr", phoneCode: "+298" },
  { code: "GL", name: "Greenland", hasStates: false, zipLabel: "Postnummer", phoneCode: "+299" },
  { code: "SJ", name: "Svalbard and Jan Mayen", hasStates: false, zipLabel: "Postkode", phoneCode: "+47" },
  { code: "AX", name: "Åland Islands", hasStates: false, zipLabel: "Postnummer", phoneCode: "+358" },
  { code: "CW", name: "Curaçao", hasStates: false, zipLabel: "Postcode", phoneCode: "+599" },
  { code: "SX", name: "Sint Maarten", hasStates: false, zipLabel: "Postcode", phoneCode: "+1" },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba", hasStates: false, zipLabel: "Postcode", phoneCode: "+599" },
  { code: "AW", name: "Aruba", hasStates: false, zipLabel: "Postcode", phoneCode: "+297" },
  { code: "AI", name: "Anguilla", hasStates: false, zipLabel: "Postcode", phoneCode: "+1" },
  { code: "BM", name: "Bermuda", hasStates: false, zipLabel: "Postcode", phoneCode: "+1" },
  { code: "VG", name: "British Virgin Islands", hasStates: false, zipLabel: "Postcode", phoneCode: "+1" },
  { code: "KY", name: "Cayman Islands", hasStates: false, zipLabel: "Postcode", phoneCode: "+1" },
  { code: "MS", name: "Montserrat", hasStates: false, zipLabel: "Postcode", phoneCode: "+1" },
  { code: "TC", name: "Turks and Caicos Islands", hasStates: false, zipLabel: "Postcode", phoneCode: "+1" },
  { code: "VI", name: "U.S. Virgin Islands", hasStates: false, zipLabel: "Postcode", phoneCode: "+1" },
  { code: "AS", name: "American Samoa", hasStates: false, zipLabel: "ZIP Code", phoneCode: "+1" },
  { code: "GU", name: "Guam", hasStates: false, zipLabel: "ZIP Code", phoneCode: "+1" },
  { code: "MP", name: "Northern Mariana Islands", hasStates: false, zipLabel: "ZIP Code", phoneCode: "+1" },
  { code: "PR", name: "Puerto Rico", hasStates: false, zipLabel: "ZIP Code", phoneCode: "+1" },
  { code: "UM", name: "United States Minor Outlying Islands", hasStates: false, zipLabel: "ZIP Code", phoneCode: "+1" },
  { code: "HK", name: "Hong Kong", hasStates: false, zipLabel: "Postal Code", phoneCode: "+852" },
  { code: "MO", name: "Macau", hasStates: false, zipLabel: "Código Postal", phoneCode: "+853" },
  { code: "TW", name: "Taiwan", hasStates: false, zipLabel: "郵遞區號", phoneCode: "+886" },
  { code: "MN", name: "Mongolia", hasStates: false, zipLabel: "Zip Code", phoneCode: "+976" },
  { code: "KZ", name: "Kazakhstan", hasStates: false, zipLabel: "Индекс", phoneCode: "+7" },
  { code: "UZ", name: "Uzbekistan", hasStates: false, zipLabel: "Pochta indeksi", phoneCode: "+998" },
  { code: "KG", name: "Kyrgyzstan", hasStates: false, zipLabel: "Почта индекси", phoneCode: "+996" },
  { code: "TJ", name: "Tajikistan", hasStates: false, zipLabel: "Индекси почта", phoneCode: "+992" },
  { code: "TM", name: "Turkmenistan", hasStates: false, zipLabel: "Poçta kody", phoneCode: "+993" },
  { code: "AF", name: "Afghanistan", hasStates: false, zipLabel: "Postal Code", phoneCode: "+93" },
  { code: "IQ", name: "Iraq", hasStates: false, zipLabel: "Postal Code", phoneCode: "+964" },
  { code: "IR", name: "Iran", hasStates: false, zipLabel: "کد پستی", phoneCode: "+98" },
  { code: "SY", name: "Syria", hasStates: false, zipLabel: "رمز بريدي", phoneCode: "+963" },
  { code: "LB", name: "Lebanon", hasStates: false, zipLabel: "رمز بريدي", phoneCode: "+961" },
  { code: "JO", name: "Jordan", hasStates: false, zipLabel: "رمز بريدي", phoneCode: "+962" },
  { code: "KW", name: "Kuwait", hasStates: false, zipLabel: "رمز بريدي", phoneCode: "+965" },
  { code: "QA", name: "Qatar", hasStates: false, zipLabel: "Postal Code", phoneCode: "+974" },
  { code: "BH", name: "Bahrain", hasStates: false, zipLabel: "Postal Code", phoneCode: "+973" },
  { code: "OM", name: "Oman", hasStates: false, zipLabel: "Postal Code", phoneCode: "+968" },
  { code: "YE", name: "Yemen", hasStates: false, zipLabel: "Postal Code", phoneCode: "+967" },
  { code: "PS", name: "Palestine", hasStates: false, zipLabel: "Postal Code", phoneCode: "+970" },
  { code: "AM", name: "Armenia", hasStates: false, zipLabel: "Հայտարարագրություն", phoneCode: "+374" },
  { code: "AZ", name: "Azerbaijan", hasStates: false, zipLabel: "Poçt kodu", phoneCode: "+994" },
  { code: "GE", name: "Georgia", hasStates: false, zipLabel: "საფოსტო ინდექსი", phoneCode: "+995" },
  { code: "BY", name: "Belarus", hasStates: false, zipLabel: "Паштовы індэкс", phoneCode: "+375" },
  { code: "UA", name: "Ukraine", hasStates: false, zipLabel: "Поштовий індекс", phoneCode: "+380" },
  { code: "MD", name: "Moldova", hasStates: false, zipLabel: "Cod poștal", phoneCode: "+373" },
  { code: "XK", name: "Kosovo", hasStates: false, zipLabel: "Postcode", phoneCode: "+383" },
];

// Comprehensive states/provinces/territories data
export const subdivisions: Record<string, Subdivision[]> = {
  US: [
    { code: "AL", name: "Alabama" },
    { code: "AK", name: "Alaska" },
    { code: "AZ", name: "Arizona" },
    { code: "AR", name: "Arkansas" },
    { code: "CA", name: "California" },
    { code: "CO", name: "Colorado" },
    { code: "CT", name: "Connecticut" },
    { code: "DE", name: "Delaware" },
    { code: "FL", name: "Florida" },
    { code: "GA", name: "Georgia" },
    { code: "HI", name: "Hawaii" },
    { code: "ID", name: "Idaho" },
    { code: "IL", name: "Illinois" },
    { code: "IN", name: "Indiana" },
    { code: "IA", name: "Iowa" },
    { code: "KS", name: "Kansas" },
    { code: "KY", name: "Kentucky" },
    { code: "LA", name: "Louisiana" },
    { code: "ME", name: "Maine" },
    { code: "MD", name: "Maryland" },
    { code: "MA", name: "Massachusetts" },
    { code: "MI", name: "Michigan" },
    { code: "MN", name: "Minnesota" },
    { code: "MS", name: "Mississippi" },
    { code: "MO", name: "Missouri" },
    { code: "MT", name: "Montana" },
    { code: "NE", name: "Nebraska" },
    { code: "NV", name: "Nevada" },
    { code: "NH", name: "New Hampshire" },
    { code: "NJ", name: "New Jersey" },
    { code: "NM", name: "New Mexico" },
    { code: "NY", name: "New York" },
    { code: "NC", name: "North Carolina" },
    { code: "ND", name: "North Dakota" },
    { code: "OH", name: "Ohio" },
    { code: "OK", name: "Oklahoma" },
    { code: "OR", name: "Oregon" },
    { code: "PA", name: "Pennsylvania" },
    { code: "RI", name: "Rhode Island" },
    { code: "SC", name: "South Carolina" },
    { code: "SD", name: "South Dakota" },
    { code: "TN", name: "Tennessee" },
    { code: "TX", name: "Texas" },
    { code: "UT", name: "Utah" },
    { code: "VT", name: "Vermont" },
    { code: "VA", name: "Virginia" },
    { code: "WA", name: "Washington" },
    { code: "WV", name: "West Virginia" },
    { code: "WI", name: "Wisconsin" },
    { code: "WY", name: "Wyoming" },
    { code: "DC", name: "District of Columbia" },
    { code: "AS", name: "American Samoa" },
    { code: "GU", name: "Guam" },
    { code: "MP", name: "Northern Mariana Islands" },
    { code: "PR", name: "Puerto Rico" },
    { code: "UM", name: "United States Minor Outlying Islands" },
    { code: "VI", name: "U.S. Virgin Islands" },
  ],
  CA: [
    { code: "AB", name: "Alberta" },
    { code: "BC", name: "British Columbia" },
    { code: "MB", name: "Manitoba" },
    { code: "NB", name: "New Brunswick" },
    { code: "NL", name: "Newfoundland and Labrador" },
    { code: "NS", name: "Nova Scotia" },
    { code: "ON", name: "Ontario" },
    { code: "PE", name: "Prince Edward Island" },
    { code: "QC", name: "Quebec" },
    { code: "SK", name: "Saskatchewan" },
    { code: "NT", name: "Northwest Territories" },
    { code: "NU", name: "Nunavut" },
    { code: "YT", name: "Yukon" },
  ],
  AU: [
    { code: "ACT", name: "Australian Capital Territory" },
    { code: "NSW", name: "New South Wales" },
    { code: "NT", name: "Northern Territory" },
    { code: "QLD", name: "Queensland" },
    { code: "SA", name: "South Australia" },
    { code: "TAS", name: "Tasmania" },
    { code: "VIC", name: "Victoria" },
    { code: "WA", name: "Western Australia" },
  ],
  DE: [
    { code: "BW", name: "Baden-Württemberg" },
    { code: "BY", name: "Bayern" },
    { code: "BE", name: "Berlin" },
    { code: "BB", name: "Brandenburg" },
    { code: "HB", name: "Bremen" },
    { code: "HH", name: "Hamburg" },
    { code: "HE", name: "Hessen" },
    { code: "MV", name: "Mecklenburg-Vorpommern" },
    { code: "NI", name: "Niedersachsen" },
    { code: "NW", name: "Nordrhein-Westfalen" },
    { code: "RP", name: "Rheinland-Pfalz" },
    { code: "SL", name: "Saarland" },
    { code: "SN", name: "Sachsen" },
    { code: "ST", name: "Sachsen-Anhalt" },
    { code: "SH", name: "Schleswig-Holstein" },
    { code: "TH", name: "Thüringen" },
  ],
  IN: [
    { code: "AP", name: "Andhra Pradesh" },
    { code: "AR", name: "Arunachal Pradesh" },
    { code: "AS", name: "Assam" },
    { code: "BR", name: "Bihar" },
    { code: "CG", name: "Chhattisgarh" },
    { code: "GA", name: "Goa" },
    { code: "GJ", name: "Gujarat" },
    { code: "HR", name: "Haryana" },
    { code: "HP", name: "Himachal Pradesh" },
    { code: "JK", name: "Jammu and Kashmir" },
    { code: "JH", name: "Jharkhand" },
    { code: "KA", name: "Karnataka" },
    { code: "KL", name: "Kerala" },
    { code: "MP", name: "Madhya Pradesh" },
    { code: "MH", name: "Maharashtra" },
    { code: "MN", name: "Manipur" },
    { code: "ML", name: "Meghalaya" },
    { code: "MZ", name: "Mizoram" },
    { code: "NL", name: "Nagaland" },
    { code: "OR", name: "Odisha" },
    { code: "PB", name: "Punjab" },
    { code: "RJ", name: "Rajasthan" },
    { code: "SK", name: "Sikkim" },
    { code: "TN", name: "Tamil Nadu" },
    { code: "TG", name: "Telangana" },
    { code: "TR", name: "Tripura" },
    { code: "UP", name: "Uttar Pradesh" },
    { code: "UT", name: "Uttarakhand" },
    { code: "WB", name: "West Bengal" },
    { code: "AN", name: "Andaman and Nicobar Islands" },
    { code: "CH", name: "Chandigarh" },
    { code: "DN", name: "Dadra and Nagar Haveli" },
    { code: "DD", name: "Daman and Diu" },
    { code: "DL", name: "Delhi" },
    { code: "JK", name: "Jammu and Kashmir" },
    { code: "LA", name: "Ladakh" },
    { code: "LD", name: "Lakshadweep" },
    { code: "PY", name: "Puducherry" },
  ],
  BR: [
    { code: "AC", name: "Acre" },
    { code: "AL", name: "Alagoas" },
    { code: "AP", name: "Amapá" },
    { code: "AM", name: "Amazonas" },
    { code: "BA", name: "Bahia" },
    { code: "CE", name: "Ceará" },
    { code: "DF", name: "Distrito Federal" },
    { code: "ES", name: "Espírito Santo" },
    { code: "GO", name: "Goiás" },
    { code: "MA", name: "Maranhão" },
    { code: "MT", name: "Mato Grosso" },
    { code: "MS", name: "Mato Grosso do Sul" },
    { code: "MG", name: "Minas Gerais" },
    { code: "PA", name: "Pará" },
    { code: "PB", name: "Paraíba" },
    { code: "PR", name: "Paraná" },
    { code: "PE", name: "Pernambuco" },
    { code: "PI", name: "Piauí" },
    { code: "RJ", name: "Rio de Janeiro" },
    { code: "RN", name: "Rio Grande do Norte" },
    { code: "RS", name: "Rio Grande do Sul" },
    { code: "RO", name: "Rondônia" },
    { code: "RR", name: "Roraima" },
    { code: "SC", name: "Santa Catarina" },
    { code: "SP", name: "São Paulo" },
    { code: "SE", name: "Sergipe" },
    { code: "TO", name: "Tocantins" },
  ],
  MX: [
    { code: "AG", name: "Aguascalientes" },
    { code: "BC", name: "Baja California" },
    { code: "BS", name: "Baja California Sur" },
    { code: "CM", name: "Campeche" },
    { code: "CO", name: "Coahuila" },
    { code: "CL", name: "Colima" },
    { code: "DF", name: "Ciudad de México" },
    { code: "DG", name: "Durango" },
    { code: "GT", name: "Guanajuato" },
    { code: "GR", name: "Guerrero" },
    { code: "HG", name: "Hidalgo" },
    { code: "JA", name: "Jalisco" },
    { code: "EM", name: "Estado de México" },
    { code: "MI", name: "Michoacán" },
    { code: "MO", name: "Morelos" },
    { code: "NA", name: "Nayarit" },
    { code: "NL", name: "Nuevo León" },
    { code: "OA", name: "Oaxaca" },
    { code: "PU", name: "Puebla" },
    { code: "QT", name: "Querétaro" },
    { code: "QR", name: "Quintana Roo" },
    { code: "SL", name: "San Luis Potosí" },
    { code: "SI", name: "Sinaloa" },
    { code: "SO", name: "Sonora" },
    { code: "TB", name: "Tabasco" },
    { code: "TM", name: "Tamaulipas" },
    { code: "TL", name: "Tlaxcala" },
    { code: "VE", name: "Veracruz" },
    { code: "YU", name: "Yucatán" },
    { code: "ZA", name: "Zacatecas" },
  ],
  NG: [
    { code: "AB", name: "Abia" },
    { code: "AD", name: "Adamawa" },
    { code: "AK", name: "Akwa Ibom" },
    { code: "AN", name: "Anambra" },
    { code: "BA", name: "Bauchi" },
    { code: "BY", name: "Bayelsa" },
    { code: "BE", name: "Benue" },
    { code: "BO", name: "Borno" },
    { code: "CR", name: "Cross River" },
    { code: "DE", name: "Delta" },
    { code: "EB", name: "Ebonyi" },
    { code: "ED", name: "Edo" },
    { code: "EK", name: "Ekiti" },
    { code: "EN", name: "Enugu" },
    { code: "FC", name: "Federal Capital Territory" },
    { code: "GO", name: "Gombe" },
    { code: "IM", name: "Imo" },
    { code: "JI", name: "Jigawa" },
    { code: "KD", name: "Kaduna" },
    { code: "KN", name: "Kano" },
    { code: "KT", name: "Katsina" },
    { code: "KE", name: "Kebbi" },
    { code: "KO", name: "Kogi" },
    { code: "KW", name: "Kwara" },
    { code: "LA", name: "Lagos" },
    { code: "NA", name: "Nasarawa" },
    { code: "NI", name: "Niger" },
    { code: "OG", name: "Ogun" },
    { code: "ON", name: "Ondo" },
    { code: "OS", name: "Osun" },
    { code: "OY", name: "Oyo" },
    { code: "PL", name: "Plateau" },
    { code: "RI", name: "Rivers" },
    { code: "SO", name: "Sokoto" },
    { code: "TA", name: "Taraba" },
    { code: "YO", name: "Yobe" },
    { code: "ZA", name: "Zamfara" },
  ],
  CN: [
    { code: "11", name: "北京市" },
    { code: "12", name: "天津市" },
    { code: "13", name: "河北省" },
    { code: "14", name: "山西省" },
    { code: "15", name: "内蒙古自治区" },
    { code: "21", name: "辽宁省" },
    { code: "22", name: "吉林省" },
    { code: "23", name: "黑龙江省" },
    { code: "31", name: "上海市" },
    { code: "32", name: "江苏省" },
    { code: "33", name: "浙江省" },
    { code: "34", name: "安徽省" },
    { code: "35", name: "福建省" },
    { code: "36", name: "江西省" },
    { code: "37", name: "山东省" },
    { code: "41", name: "河南省" },
    { code: "42", name: "湖北省" },
    { code: "43", name: "湖南省" },
    { code: "44", name: "广东省" },
    { code: "45", name: "广西壮族自治区" },
    { code: "46", name: "海南省" },
    { code: "50", name: "重庆市" },
    { code: "51", name: "四川省" },
    { code: "52", name: "贵州省" },
    { code: "53", name: "云南省" },
    { code: "54", name: "西藏自治区" },
    { code: "61", name: "陕西省" },
    { code: "62", name: "甘肃省" },
    { code: "63", name: "青海省" },
    { code: "64", name: "宁夏回族自治区" },
    { code: "65", name: "新疆维吾尔自治区" },
    { code: "71", name: "台湾省" },
    { code: "81", name: "香港特别行政区" },
    { code: "82", name: "澳门特别行政区" },
  ],
  MY: [
    { code: "01", name: "Johor" },
    { code: "02", name: "Kedah" },
    { code: "03", name: "Kelantan" },
    { code: "04", name: "Melaka" },
    { code: "05", name: "Negeri Sembilan" },
    { code: "06", name: "Pahang" },
    { code: "07", name: "Pulau Pinang" },
    { code: "08", name: "Perak" },
    { code: "09", name: "Perlis" },
    { code: "10", name: "Selangor" },
    { code: "11", name: "Terengganu" },
    { code: "12", name: "Sabah" },
    { code: "13", name: "Sarawak" },
    { code: "14", name: "Wilayah Persekutuan Kuala Lumpur" },
    { code: "15", name: "Wilayah Persekutuan Labuan" },
    { code: "16", name: "Wilayah Persekutuan Putrajaya" },
  ],
  ID: [
    { code: "AC", name: "Aceh" },
    { code: "BA", name: "Bali" },
    { code: "BB", name: "Bangka Belitung" },
    { code: "BE", name: "Bengkulu" },
    { code: "BT", name: "Banten" },
    { code: "GO", name: "Gorontalo" },
    { code: "JA", name: "Jambi" },
    { code: "JB", name: "Jawa Barat" },
    { code: "JI", name: "Jawa Timur" },
    { code: "JK", name: "Jakarta Raya" },
    { code: "JT", name: "Jawa Tengah" },
    { code: "KB", name: "Kalimantan Barat" },
    { code: "KI", name: "Kalimantan Timur" },
    { code: "KR", name: "Kepulauan Riau" },
    { code: "KS", name: "Kalimantan Selatan" },
    { code: "KT", name: "Kalimantan Tengah" },
    { code: "KU", name: "Kalimantan Utara" },
    { code: "LA", name: "Lampung" },
    { code: "MA", name: "Maluku" },
    { code: "MU", name: "Maluku Utara" },
    { code: "NB", name: "Nusa Tenggara Barat" },
    { code: "NT", name: "Nusa Tenggara Timur" },
    { code: "PA", name: "Papua" },
    { code: "PB", name: "Papua Barat" },
    { code: "RI", name: "Riau" },
    { code: "SA", name: "Sulawesi Utara" },
    { code: "SB", name: "Sumatera Barat" },
    { code: "SG", name: "Sulawesi Tenggara" },
    { code: "SN", name: "Sulawesi Selatan" },
    { code: "SR", name: "Sulawesi Barat" },
    { code: "SS", name: "Sumatera Selatan" },
    { code: "ST", name: "Sulawesi Tengah" },
    { code: "SU", name: "Sumatera Utara" },
    { code: "YO", name: "Yogyakarta" },
  ],
  PK: [
    { code: "PK-PB", name: "Punjab" },
    { code: "PK-SD", name: "Sindh" },
    { code: "PK-BA", name: "Balochistan" },
    { code: "PK-KP", name: "Khyber Pakhtunkhwa" },
    { code: "PK-TA", name: "Federally Administered Tribal Areas" },
    { code: "PK-IS", name: "Islamabad Capital Territory" },
    { code: "PK-JK", name: "Azad Jammu and Kashmir" },
    { code: "PK-GB", name: "Gilgit-Baltistan" },
  ],
  AR: [
    { code: "A", name: "Salta" },
    { code: "B", name: "Buenos Aires Province" },
    { code: "C", name: "Buenos Aires" },
    { code: "D", name: "San Luis" },
    { code: "E", name: "Entre Ríos" },
    { code: "F", name: "La Rioja" },
    { code: "G", name: "Santiago del Estero" },
    { code: "H", name: "Chaco" },
    { code: "J", name: "San Juan" },
    { code: "K", name: "Catamarca" },
    { code: "L", name: "La Pampa" },
    { code: "M", name: "Mendoza" },
    { code: "N", name: "Misiones" },
    { code: "P", name: "Formosa" },
    { code: "Q", name: "Neuquén" },
    { code: "R", name: "Río Negro" },
    { code: "S", name: "Santa Fe" },
    { code: "T", name: "Tucumán" },
    { code: "U", name: "Chubut" },
    { code: "V", name: "Tierra del Fuego" },
    { code: "W", name: "Corrientes" },
    { code: "X", name: "Córdoba" },
    { code: "Y", name: "Jujuy" },
    { code: "Z", name: "Santa Cruz" },
  ],
  CO: [
    { code: "AMA", name: "Amazonas" },
    { code: "ANT", name: "Antioquia" },
    { code: "ARA", name: "Arauca" },
    { code: "ATL", name: "Atlántico" },
    { code: "BOL", name: "Bolívar" },
    { code: "BOY", name: "Boyacá" },
    { code: "CAL", name: "Caldas" },
    { code: "CAQ", name: "Caquetá" },
    { code: "CAS", name: "Casanare" },
    { code: "CAU", name: "Cauca" },
    { code: "CES", name: "Cesar" },
    { code: "CHO", name: "Chocó" },
    { code: "COR", name: "Córdoba" },
    { code: "CUN", name: "Cundinamarca" },
    { code: "DC", name: "Distrito Capital de Bogotá" },
    { code: "GUA", name: "Guainía" },
    { code: "GUV", name: "Guaviare" },
    { code: "HUI", name: "Huila" },
    { code: "LAG", name: "La Guajira" },
    { code: "MAG", name: "Magdalena" },
    { code: "MET", name: "Meta" },
    { code: "NAR", name: "Nariño" },
    { code: "NSA", name: "Norte de Santander" },
    { code: "PUT", name: "Putumayo" },
    { code: "QUI", name: "Quindío" },
    { code: "RIS", name: "Risaralda" },
    { code: "SAN", name: "Santander" },
    { code: "SAP", name: "San Andrés, Providencia y Santa Catalina" },
    { code: "SUC", name: "Sucre" },
    { code: "TOL", name: "Tolima" },
    { code: "VAC", name: "Valle del Cauca" },
    { code: "VAU", name: "Vaupés" },
    { code: "VID", name: "Vichada" },
  ],
  PE: [
    { code: "AMA", name: "Amazonas" },
    { code: "ANC", name: "Ancash" },
    { code: "APU", name: "Apurímac" },
    { code: "ARE", name: "Arequipa" },
    { code: "AYA", name: "Ayacucho" },
    { code: "CAJ", name: "Cajamarca" },
    { code: "CAL", name: "Callao" },
    { code: "CUS", name: "Cusco" },
    { code: "HUC", name: "Huánuco" },
    { code: "HUV", name: "Huancavelica" },
    { code: "ICA", name: "Ica" },
    { code: "JUN", name: "Junín" },
    { code: "LAL", name: "La Libertad" },
    { code: "LAM", name: "Lambayeque" },
    { code: "LIM", name: "Lima" },
    { code: "LOR", name: "Loreto" },
    { code: "MDD", name: "Madre de Dios" },
    { code: "MOQ", name: "Moquegua" },
    { code: "PAS", name: "Pasco" },
    { code: "PIU", name: "Piura" },
    { code: "PUN", name: "Puno" },
    { code: "SAM", name: "San Martín" },
    { code: "TAC", name: "Tacna" },
    { code: "TUM", name: "Tumbes" },
    { code: "UCA", name: "Ucayali" },
  ],
  CL: [
    { code: "AI", name: "Aisén del General Carlos Ibañez del Campo" },
    { code: "AN", name: "Antofagasta" },
    { code: "AP", name: "Arica y Parinacota" },
    { code: "AT", name: "Atacama" },
    { code: "BI", name: "Biobío" },
    { code: "CO", name: "Coquimbo" },
    { code: "LI", name: "Libertador General Bernardo O'Higgins" },
    { code: "LL", name: "Los Lagos" },
    { code: "LR", name: "Los Ríos" },
    { code: "MA", name: "Magallanes y de la Antártica Chilena" },
    { code: "ML", name: "Maule" },
    { code: "NB", name: "Ñuble" },
    { code: "RM", name: "Región Metropolitana de Santiago" },
    { code: "TA", name: "Tarapacá" },
    { code: "VS", name: "Valparaíso" },
  ],
};

// Helper functions
export const getCountryByCode = (code: string): Country | undefined => {
  return countries.find(country => country.code === code);
};

export const getSubdivisionsByCountry = (countryCode: string): Subdivision[] => {
  return subdivisions[countryCode] || [];
};

export const getCountryName = (code: string): string => {
  const country = getCountryByCode(code);
  return country ? country.name : code;
};

export const getSubdivisionName = (countryCode: string, subdivisionCode: string): string => {
  const subdivisions = getSubdivisionsByCountry(countryCode);
  const subdivision = subdivisions.find(sub => sub.code === subdivisionCode);
  return subdivision ? subdivision.name : subdivisionCode;
};